# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Get Branch Name
        id: branch_name
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"

      - name: Check if Feature Branch
        id: is_feature
        run: echo "is_feature=$(echo ${{ steps.branch_name.outputs.branch }} | grep -c '^feature/')" >> "$GITHUB_OUTPUT"

      - name: Check variable
        run: |
          echo "BRANCH_NAME=${{ steps.branch_name.outputs.branch }}"
          echo "IS_FEATURE=${{ steps.is_feature.outputs.is_feature }}"

      - name: Run tests
        run: npm test
        env:
          TEST_DB: ${{ steps.branch_name.outputs.branch }} # branch 이름을 환경변수로 전달

