# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: npm install
        run: npm install

      - name: Get Branch Name
        id: branch_name
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT" # 워크플로를 실행한 branch 또는 tag의 형식에서 브랜치 명을 파싱

      - name: Check if Feature Branch
        id: is_feature
        run: echo "is_feature=$(echo ${{ steps.branch_name.outputs.branch }} | grep -c '^feature/')" >> "$GITHUB_OUTPUT" # 만약 feature 브랜치라면 1, 아니면 0

      - name: Run tests
        run: npm test
        env:
          TEST_DB: ${{ steps.branch_name.outputs.branch }} # 환경 변수로 전달
